# Lines beginning with a # are comments, and are only included for
# illustration. These comments are overkill for most inventory files.

# Application
[app]
192.168.56.66

# Group 'multi' with all servers
[multi:children]
app

# Variables that will be applied to all servers
[multi:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=/mnt/c/Users/Marc/.vagrant.d/insecure_private_key